### PR TITLE
fixed np.float to float to work with numpy > 1.20

### PR DESCRIPTION
**Pull request by LukasMacha97**
Numpy 1.24 raises an error as there is no np.float. I changed that in the code simply to just float so that it now works with the latest numpy version.

### CODE REVIEW

**Comment by HuanWeng** [comment]
Hi Lukas,

Thank you for fixing this! I just merged your first commit in. I think the others are for your personal work so I will leave them there.

**Comment by priscillascu** [comment]
收到，我会尽快给您答复。杨海鑫

**Comment by LSinterbotix** [comment]
@HuanWeng could we get this change released on PyPI?

**Comment by HuanWeng** [comment]
@LSinterbotix  Of course. Thank you for reminding us. It is planned to be done this week.

**Pull request closed without merging**
